### ISSUE TITLE
レポジトリ名

### ISSUE THREAD

**Issue by teramonagi** [japanr/japanr#8]
これ、来年以降困る事案では？？？

**Comment by kazutan** [comment]
現在のindex.htmlを2016.htmlとかにファイル名変更して，来年のは新たにindex.htmlを作成するという手もあるのかなと思いました

**Comment by gepuro** [comment]
そこまで真面目に考えてレポジトリ名を決めていなかったですが、来年以降はディレクトリを作って、
http://japanr.net/2016/index.html
みたいな構成で良いかなと思います。
